"""Run blind-JSCC plans on Kaggle GPUs, and bring the results back.

    # calibration: B and C-att, 16-QAM, seed 0
    python scripts/kaggle_jobs.py push calib --stage calibration --epochs 300

    # a week-1 slice (keep each job under Kaggle's 12 h session limit: ~4 runs)
    python scripts/kaggle_jobs.py push w1-qam-s0 --arms B C-att --mods qam16 --seeds 0 1 --epochs 250

    python scripts/kaggle_jobs.py status calib     # queued / running / complete / error
    python scripts/kaggle_jobs.py fetch calib      # download outputs, merge runs into results/
    python scripts/kaggle_jobs.py list             # every job pushed from this machine
    python -m kaggle quota                         # remaining weekly GPU hours

Each job is a private Kaggle script kernel that clones this repo **at a pinned commit**
(the current HEAD, which must already be pushed), runs scripts/run_blind.py with the given
plan, and leaves results, wandb offline logs and the job log in its output.

Pairing: every run of a comparison must use the same GPU type and num_workers, so all jobs
use one accelerator (T4 by default) and the config's num_workers. A teammate running jobs
under their own Kaggle account should use the same defaults; `--token-file` points the CLI
at their token instead of ~/.kaggle/access_token.

Credentials never enter the repo or the kernel: the token stays in the user's profile (or
the file given), and the kernel itself needs no secrets.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JOBS = ROOT / ".kaggle_jobs"
REPO_URL = "https://github.com/Subhashhari/semcom.git"
DEFAULT_ACCELERATOR = "NvidiaTeslaT4"
SLUG_PREFIX = "bjscc-"

RUNNER = '''"""Kaggle job generated by scripts/kaggle_jobs.py - do not edit by hand."""
import os, shutil, subprocess, sys

COMMIT = {commit!r}
PLAN = {plan!r}
WORK = "/kaggle/working"

def sh(*cmd, **kw):
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, **kw)

src = os.path.join(WORK, "src")
sh("git", "clone", "--quiet", {repo!r}, src)
sh("git", "-C", src, "checkout", "--quiet", COMMIT)
sh(sys.executable, "-m", "pip", "install", "--quiet", "pyyaml", "scipy", "wandb")
sh(sys.executable, "-c", "import torch; print(torch.__version__, torch.cuda.get_device_name(0))")

env = dict(os.environ, WANDB_DIR=os.path.join(WORK, "wandb"), WANDB_SILENT="true")
os.makedirs(env["WANDB_DIR"], exist_ok=True)
try:
    sh(sys.executable, "scripts/run_blind.py", *PLAN, "--wandb-mode", "offline", cwd=src, env=env)
finally:
    # Keep only what is worth downloading: results and wandb logs, not the repo or CIFAR.
    if os.path.isdir(os.path.join(src, "results")):
        shutil.copytree(os.path.join(src, "results"), os.path.join(WORK, "results"), dirs_exist_ok=True)
    shutil.rmtree(src, ignore_errors=True)
'''


def kaggle(*args, token_file: Path | None = None, capture: bool = False) -> str:
    env = dict(os.environ)
    if token_file is not None:
        env["KAGGLE_API_TOKEN"] = Path(token_file).read_text(encoding="utf-8").strip()
    proc = subprocess.run(
        [sys.executable, "-m", "kaggle", *args],
        env=env,
        text=True,
        capture_output=capture,
    )
    if proc.returncode != 0:
        raise SystemExit(f"kaggle {' '.join(args)} failed" + (f":\n{proc.stderr}" if capture else ""))
    return proc.stdout if capture else ""


def kaggle_username(token_file: Path | None) -> str:
    for line in kaggle("config", "view", token_file=token_file, capture=True).splitlines():
        if line.strip().startswith("- username:"):
            return line.split(":", 1)[1].strip()
    raise SystemExit("could not determine the Kaggle username; is the token valid?")


def pinned_commit() -> str:
    def git(*a):
        return subprocess.run(["git", *a], cwd=ROOT, text=True, capture_output=True).stdout.strip()

    if git("status", "--porcelain", "--untracked-files=no"):
        raise SystemExit("uncommitted changes to tracked files: commit (and push) before launching")
    head = git("rev-parse", "HEAD")
    git("fetch", "--quiet", "origin")
    if not git("branch", "-r", "--contains", head):
        raise SystemExit(f"HEAD {head[:7]} is not on GitHub yet: git push first")
    return head


def plan_args(args) -> list[str]:
    plan = []
    if args.stage:
        plan += ["--stage", args.stage]
    if args.arms:
        plan += ["--arms", *args.arms]
    if args.mods:
        plan += ["--mods", *args.mods]
    if args.seeds is not None:
        plan += ["--seeds", *map(str, args.seeds)]
    if args.epochs is not None:
        plan += ["--epochs", str(args.epochs)]
    if args.evaluate:
        plan.append("--evaluate")
    return plan


def job_dir(name: str) -> Path:
    return JOBS / name


def load_job(name: str) -> dict:
    path = job_dir(name) / "job.json"
    if not path.exists():
        raise SystemExit(f"no job named {name!r}; see `list`")
    return json.loads(path.read_text(encoding="utf-8"))


def cmd_push(args) -> None:
    plan = plan_args(args)
    if not plan:
        raise SystemExit("give a plan: --stage, or --arms/--mods/--seeds")
    # Dry-run the plan locally first, so a bad plan fails here rather than after a GPU wait.
    subprocess.run([sys.executable, "scripts/run_blind.py", *plan, "--dry-run"], cwd=ROOT, check=True)

    commit = pinned_commit()
    user = kaggle_username(args.token_file)
    slug = f"{SLUG_PREFIX}{args.name}".lower()
    folder = job_dir(args.name) / "kernel"
    if folder.exists():
        shutil.rmtree(folder)
    folder.mkdir(parents=True)
    (folder / "run.py").write_text(
        RUNNER.format(commit=commit, plan=plan, repo=REPO_URL), encoding="utf-8"
    )
    meta = {
        "id": f"{user}/{slug}",
        "title": slug,
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "machine_shape": args.accelerator,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (folder / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    kaggle("kernels", "push", "-p", str(folder), "--accelerator", args.accelerator,
           token_file=args.token_file)
    job = {
        "name": args.name, "kernel": meta["id"], "commit": commit, "plan": plan,
        "accelerator": args.accelerator,
        "token_file": str(args.token_file) if args.token_file else None,
    }
    (job_dir(args.name) / "job.json").write_text(json.dumps(job, indent=2), encoding="utf-8")
    print(f"pushed {meta['id']} at {commit[:7]} on {args.accelerator}")
    print(f"  https://www.kaggle.com/code/{meta['id']}")


def _token(job: dict) -> Path | None:
    return Path(job["token_file"]) if job.get("token_file") else None


def cmd_status(args) -> None:
    job = load_job(args.name)
    print(kaggle("kernels", "status", job["kernel"], token_file=_token(job), capture=True).strip())


def cmd_fetch(args) -> None:
    job = load_job(args.name)
    out = job_dir(args.name) / "output"
    out.mkdir(parents=True, exist_ok=True)
    kaggle("kernels", "output", job["kernel"], "-p", str(out), "--force", token_file=_token(job))

    merged, skipped = 0, 0
    for hist in sorted((out / "results").glob("**/history.json")):
        run_dir = hist.parent
        dest = ROOT / run_dir.relative_to(out)
        if (dest / "history.json").exists() and not args.force:
            skipped += 1
            continue
        shutil.copytree(run_dir, dest, dirs_exist_ok=True)
        merged += 1
    print(f"merged {merged} run(s) into results/" + (f", skipped {skipped} already present" if skipped else ""))
    wandb_dir = out / "wandb"
    if wandb_dir.exists():
        print(f"wandb offline logs: {wandb_dir}\n  sync with: wandb sync {wandb_dir}/offline-run-*")
    log = next(out.glob("*.log"), None)
    if log:
        print(f"job log: {log}")


def cmd_list(_args) -> None:
    if not JOBS.exists():
        print("no jobs yet")
        return
    for path in sorted(JOBS.glob("*/job.json")):
        job = json.loads(path.read_text(encoding="utf-8"))
        print(f"{job['name']:20s} {job['kernel']:40s} {job['commit'][:7]}  {' '.join(job['plan'])}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    push = sub.add_parser("push", help="launch a plan as a Kaggle GPU job")
    push.add_argument("name", help="short job name, e.g. calib or w1-qam-s0")
    push.add_argument("--stage")
    push.add_argument("--arms", nargs="+")
    push.add_argument("--mods", nargs="+")
    push.add_argument("--seeds", nargs="+", type=int)
    push.add_argument("--epochs", type=int)
    push.add_argument("--evaluate", action="store_true")
    push.add_argument("--accelerator", default=DEFAULT_ACCELERATOR)
    push.add_argument("--token-file", type=Path, default=None)
    push.set_defaults(func=cmd_push)

    for name, fn in (("status", cmd_status), ("fetch", cmd_fetch)):
        sp = sub.add_parser(name)
        sp.add_argument("name")
        if name == "fetch":
            sp.add_argument("--force", action="store_true", help="overwrite runs already present")
        sp.set_defaults(func=fn)
    sub.add_parser("list").set_defaults(func=cmd_list)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
